---
title: "Homework 2"
output: html_document
---

# Question 1
Two time series $(X_t)$ and $(Y_t)$ are *jointly* stationary if they are both stationary and their autocovariance function $\gamma_{XY}(h)$ is given by
$$\gamma_{XY}(h) = \text{Cov}(X_{t+h}, Y_t) = \mathbb{E}[(X_{t+h} - \mu_x)(Y_t - \mu_Y)],$$
where $\mu_X$ and $\mu_Y$ are the constant means of $(X_t)$ and $(Y_t)$ respectively. Consequently, the cross-correlation function between $(X_t)$ and $(Y_t)$ is defined as
$$\rho_{XY}(h) = \frac{\gamma_{XY}(h)}{\sqrt{\gamma_{X}(0)}\sqrt{\gamma_{Y}(0)}}.$$
Show that $\rho_{XY}(h) = \rho_{YX}(-h)$.

---  



\pagebreak  


# Question 2

A time series with a periodic component can be constructed as follows:
$$
X_t = U_1 sin(2\pi \omega_0 t) + U_2 cos(2\pi \omega_0 t),
$$
where $U_1$, $U_2$ are independent random variables with zero means and $E(U_1^2) = E(U_2^2) = \sigma^2$. The constant $\omega_0$ determines the period or time it takes the process to make one complete cycle. Show that this series is weakly stationary with autocovariance function
$$
\gamma(h) = \sigma^2 cos(2\pi \omega_0 h).
$$


\pagebreak  

# Question 3
Consider the two series
$$
X_t = W_t, \\
Y_t = W_t - \theta W_{t-1} + U_t,
$$
where $W_t$ and $U_t$ are independent white noise series with variances $\sigma_w^2$ and $\sigma_u^2$, respectively, and $\theta$ is an unspecified constant.

1. Express the autocorrelation function of $(Y_t)$, $\rho_Y(h)$, for $h=0, \pm 1, \pm 2, \ldots$ as a function of $\sigma_w^2$, $\sigma_u^2$ and $\theta$.
2. Using the information in Question 1:
    a) Determine the cross-correlation function, $\rho_{XY}(h)$ relating $(X_t)$ and $(Y_t)$.
    b) Show that $(X_t)$ and $(Y_t)$ are jointly stationary.



\pagebreak  

# Question 4
Consider a time series given by
$$
X_t = R_t + Y_t,
$$
such that $Y_t$ is a stationary process and $R_t$ denotes a random walk with drift model defined as
$$
R_t = \omega + R_{t-1} + W_t,
$$
where $\omega$ is a constant and $W_t$ is a white noise process with variance $\sigma_w^2$. Show that under a difference operation, $X_t$ is stationary (i.e. $Z_t = \delta X_t = X_t - X_{t-1}$ is stationary). 



\pagebreak  


# Question 5
Consider the symmetric moving average process
$$
X_t = \frac{1}{2q+1} \sum_{j=-q}^{q} Y_{t+j},
$$
where
$$
Y_t = a+bt+W_t,
$$
with $a$ and $b$ being constants and $W_t$ being a white noise process with variance $\sigma_w^2$, $t=0, \pm 1, \ldots, \pm T$. Find the mean function and autocorrelation function of the process $(X_t)$. 

Hint: Even though the process is not stationary, the autocorrelation function of ${X_t}$ should only depend on h. 



\pagebreak  


# Question 6  
An MA(1) model is defined as follows:
$$X_t = W_t + \theta W_{t−1}.$$

1. Show that $\big|\rho_X(1)\big| \leq \frac{1}{2}$ for any value of $\theta$. 
2. For which values of $\theta$ does $\rho_X(1)$ attain its maximum and minimum?



\pagebreak  


# Question 7 
Let $W_t$ be white noise with variance $\sigma_w^2$ and let $|\phi|<1$ be a constant. Assume that $X_1 = W_1$, and 
$$
X_t = \phi X_{t-1} + W_t, \;\;\; t=2,3, \ldots
$$

1. Find the mean and the variance of $\{X_t: t=1,2, \ldots\}$. Is $X_t$ stationary?

2. Show that
$$
\text{corr}(X_t, X_{t-h}) = \phi^h \Bigg( \frac{\text{Var}(X_{t-h})}{\text{Var}(X_t)} \Bigg) ^{1/2}
$$
for $h \geq 0$.

3. Argue that for "large" t,
$$
\text{Var} (X_t) \approx \frac{\sigma_w^2}{1-\phi^2}
$$
and 
$$
\text{corr}(X_t, X_{t-h}) \approx \phi^h,
$$
for $h\geq 0$ (i.e. $X_t$ is "asymptotically stationary").

4. Suppose $$X_1 = \frac{W_1}{\sqrt{1-\phi^2}}.$$ Is this process stationary?

5. Comment on how you could use these results to simulate $T$ observations of a stationary AR(1) model using values simulated from an iid $\mathcal{N}(0,1)$.
